AllCops:
  Includes:
    - '**/Rakefile'
    - '**/Gemfile'

Documentation:
  Enabled: false

LineLength:
  Max: 100

MethodLength:
  Max: 12

RegexpLiteral:
  Enabled: false

Validation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

AndOr:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

AsciiComments:
  Enabled: false

Encoding:
  Enabled: false

ClassLength:
  Enabled: false

Blocks:
  Enabled: false

ConstantName:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false
