AllCops:
  Includes:
    - '**/Rakefile'
    - '**/Gemfile'

AndOr:
  Enabled: false

AsciiComments:
  Enabled: false

Blocks:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

ConstantName:
  Enabled: false

Documentation:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 120

MethodLength:
  Max: 12

RegexpLiteral:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

Validation:
  Enabled: false

Style/PredicateName:
  Enabled: false
